// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU7MjfLV4dFGGLBfMIvjyesDr4F89ue3U',
    appId: '1:411278175067:web:50dedba47f0ed9764a887e',
    messagingSenderId: '411278175067',
    projectId: 'mobil-6fcb0',
    authDomain: 'mobil-6fcb0.firebaseapp.com',
    storageBucket: 'mobil-6fcb0.appspot.com',
    measurementId: 'G-G3ZVQ4DVDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxq74zFlG1dC8rrI-E0WOZ7c6fjeHKJbE',
    appId: '1:411278175067:android:f33f6e19c6b345d34a887e',
    messagingSenderId: '411278175067',
    projectId: 'mobil-6fcb0',
    storageBucket: 'mobil-6fcb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4Q1OduQDyN4IAVSIomgt6wHTawSB23I',
    appId: '1:411278175067:ios:6728c83b3194e4a34a887e',
    messagingSenderId: '411278175067',
    projectId: 'mobil-6fcb0',
    storageBucket: 'mobil-6fcb0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4Q1OduQDyN4IAVSIomgt6wHTawSB23I',
    appId: '1:411278175067:ios:30c53a62ce07f7604a887e',
    messagingSenderId: '411278175067',
    projectId: 'mobil-6fcb0',
    storageBucket: 'mobil-6fcb0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
